version: '3.8'

services:
  app:
    build: .
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
