version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3333:80"   # Mapping du port 3333 sur l'hôte vers le port 80 du container
    networks:
      - app-network

  server:
    build:
      context: ./server
    ports:
      - "5001:5001"  # Mapping du port 5001 sur l'hôte vers le port 5001 du container
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
