version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/client
    command: ["pnpm", "run", "dev"]
    ports:
      - "3333:3333"
    volumes:
      - ./client:/usr/src/app/client

  server:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app/server
    command: ["pnpm", "run", "start"]
    ports:
      - "5001:5001"
    volumes:
      - ./server:/usr/src/app/server